name: 'dbt_artifacts'
version: '0.1.0'
config-version: 2
require-dbt-version: ">=0.20.0"

models:
  dbt_artifacts:
    +schema: dbt_artifacts_pkg
    +materialized: table
    incremental:
      +materialized: incremental
    staging:
      +materialized: view