name: "dbt_artifacts"
version: "2.6.2"
config-version: 2
require-dbt-version: [">=1.3.0", "<1.8.0"]
profile: "dbt_artifacts"

clean-targets: # folders to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

models:
  dbt_artifacts:
    +materialized: view
    +file_format: "{% if target.type == 'athena' %}parquet[% else %}delta{% endif %}"
    +table_type: "{% if target.type == 'athena' %}iceberg{% endif %}"
    +incremental_strategy: "{% if target.type == 'athena' %}append{% endif %}"
    sources:
      +materialized: incremental
      +on_schema_change: append_new_columns
      +full_refresh: false
      +persist_docs:
        # Databricks doesn't offer column-level support for persisting docs
        columns: '{{ target.name != "databricks" }}'

