name: 'dbt_artifacts'
version: '0.1.0'
config-version: 2

profile: 'tails_analytics_profile'

models:
  dbt_artifacts:
    +schema: mart_engineering
    +materialized: table
    staging:
      +schema: base
      +materialized: view


vars:
  dbt_artifacts:
    dbt_artifacts_database: dbt_audit_db
    dbt_artifacts_schema: public
    dbt_artifacts_table: dbt_run_results_v4
