name: 'dbt_artifacts'
version: '0.1.0'
config-version: 2
profile: mack_weldon_snowflake
require-dbt-version: "<2.0.0"

models:
  dbt_artifacts:
    +schema: dbt_artifacts_pkg
    +materialized: table
    incremental:
      +materialized: incremental
    staging:
      +materialized: view