version: 2

sources:
  - name: dummy_source
    database: "{% if target.type not in ('spark', 'databricks') %}{{ var('dbt_artifacts_database', target.database) }}{% endif %}"
    schema: "{{ target.schema }}"
    freshness:
      error_after: {count: 24, period: hour}
      filter: dayname(updatedat) not in ('Sunday', 'Monday')
    loaded_at_field: convert_timezone('UTC', load_timestamp)
    meta: 
      real_name: facebook
    
    tables:
      - name: doesnt_exist
        meta:
          type: ['mermaid', 'unicorn', 'santa claus']
      - name: '"GROUP"'

