name: 'artifacts_integration_tests'
version: '1.0'
config-version: 2

profile: 'dbt_artifacts'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_modules"]

vars:
  dbt_artifacts:
    dbt_artifacts_database: "{{ env_var('SNOWFLAKE_TEST_DATABASE') }}"
    dbt_artifacts_schema: "dbt_artifacts_test_commit_{{ env_var('GITHUB_SHA') }}"

models:
    +persist_docs:
      relation: true
      columns: true
seeds:
  +quote_columns: false
