name: SQL CI test package

on:
  workflow_dispatch:
  # all PRs, important to note that `pull_request_target` workflows
  # will run in the context of the target branch of a PR
  pull_request_target:

jobs:
  integration-sqlserver:
    runs-on: ubuntu-latest
    steps:
    - name: my-step
      run: echo "Hello World!"

    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'
        architecture: 'x64'

    - name: Install SQL Server
      run: docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=1StrongPwd!!" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest

    - name: Install Microsoft ODBC
      run: sudo ACCEPT_EULA=Y apt-get install msodbcsql18 -y

    - name: Install tox
      run: python3 -m pip install tox

    - name: Run SQL Server Tests
      run: tox -e integration_sqlserver
